Make uvicorn run in background with BSD daemon(8)
and don't leave any variables behind; my mind is
exploding at the thought of namespace pollution! (:

diff --git a/engine-etc/dkwk b/engine-etc/dkwk
--- a/engine-etc/dkwk
+++ b/engine-etc/dkwk
@@ -4,6 +4,9 @@
 # REQUIRE: DAEMON cleanvar
 # KEYWORD: shutdown
 
+# shellcheck disable=SC3043
+#    BSD /bin/sh is capable of understanding "local".
+
 #
 # This is a FreeBSD init script.  It is to
 # be installed to /usr/local/etc/rc.d/dkwk,
@@ -21,7 +24,7 @@
 # dkwk_group (str):          Set to "www" by default.
 #                            Group to run as.
 # dkwk_run_mode (str):       Set to "750" by default.
-#                            Directory mode of "/var/run/dkwk".
+#                      Directory mode of "/var/run/dkwk" and "/var/log/dkwk".
 # dkwk_repo (str):           Set to "/var/db/dkwk/wiki.git" by default.
 #                            Path to wiki database.
 # dkwk_branch (str):         Set to "main" by default.
@@ -32,54 +35,102 @@
 #                            Path to Uvicorn ASGI server.
 # dkwk_app (str):            Set to "--factory dkwk.asgi:default" by default.
 #                            ASGI code.
+# dkwk_log (str):            No default.
+#          Log path, as passed to the -o / --output-file option of daemon(8).
 #
 
 . /etc/rc.subr
 
 name=dkwk
-rcvar=dkwk_enable
-rundir="/var/run"
-pidfile="${rundir}/${name}.pid"
+rcvar="${name}_enable"
+pidfile="/var/run/${name}.pid"
 
 # hooks! hooks?
 start_precmd=dkwk_start_pre
 
 load_rc_config $name
 
-: ${dkwk_enable:="NO"}
-: ${dkwk_owner:="www"}
-: ${dkwk_group:="www"}
+# We double-quote not because we fear of
+# splitting, but instead of glob expansion.
+# https://www.shellcheck.net/wiki/SC2223
+: "${dkwk_enable:="NO"}"
+: "${dkwk_owner:="www"}"
+: "${dkwk_group:="www"}"
 # The default prevents from wannabe users outside
 # of our group from snooping the socket directly...
 # Technically, even same-group users shouldn't need
 # permission to read, since we'd always provide a
 # direct path instead of have them guess.  But 710
 # looks ugly... well, we can argue on that later. ;)
-: ${dkwk_run_mode:="750"}
-: ${dkwk_repo:="/var/db/dkwk/wiki.git"}
-: ${dkwk_branch:="main"}
-: ${dkwk_bind:="unix:/var/run/dkwk/asgi.sock"}
-: ${dkwk_bin:="/var/db/dkwk/venv/bin/uvicorn"}
-: ${dkwk_app:="--factory dkwk.asgi:default"}
+: "${dkwk_run_mode:="750"}"
+: "${dkwk_repo:="/var/db/dkwk/wiki.git"}"
+: "${dkwk_branch:="main"}"
+: "${dkwk_bind:="unix:/var/run/dkwk/asgi.sock"}"
+: "${dkwk_bin:="/var/db/dkwk/venv/bin/uvicorn"}"
+: "${dkwk_app:="--factory dkwk.asgi:default"}"
 
-command=${dkwk_bin}
+command=/usr/sbin/daemon
+procname=${dkwk_bin}
 command_user=${dkwk_owner}
 command_group=${dkwk_group}
 
-try_bind=${dkwk_bind#unix:}
-if [ "$try_bind" != "$dkwk_bind" ]
+if [ -f "$dkwk_bin" ] && [ -r "$dkwk_bin" ]
 then
-	command_args="--uds ${try_bind}"
-else
-	bind_host="${dkwk_bind%:*}"
-	bind_port="${dkwk_bind#*:}"
-	command_args="--host ${bind_host} --port ${bind_port}"
+	if _interp="$(
+		read -r _interp < "${dkwk_bin}"
+		# This might mess up your syntax highlighter's
+		# lexer; but rest assured -- Bourne shell *can*
+		# in fact handle this madness! :^)
+		case "$_interp" in
+		\#!*)
+			# IFS splitting is intentional here.
+			# (You can warn me on the next one, shellcheck!)
+			# shellcheck disable=SC2086
+			set -- ${_interp#\#!}
+			echo $1
+			;;
+		*)
+			exit 1
+			;;
+		esac
+	)"; then
+		# Not an interpreted script?
+		# Unlikely but okay....
+		command_interpreter=$_interp
+	fi
+	unset _interp
 fi
-command_args="${command_args}${command_args:+ }${dkwk_app}"
+
+_try_bind=${dkwk_bind#unix:}
+if [ "$_try_bind" != "$dkwk_bind" ]
+then
+	command_args="--uds ${_try_bind}"
+else
+	_bind_host="${dkwk_bind%:*}"
+	_bind_port="${dkwk_bind#*:}"
+	command_args="--host ${_bind_host} --port ${_bind_port}"
+	unset _bind_host _bind_port
+fi
+unset _try_bind
+# -c : chdir( "/" )
+# -f : <>/dev/null 1>&0 2>&0
+# -R : retry for a given interval in seconds; -r : -R 1.
+#        (We will do NEITHER. :)
+# -T : syslog tag, as passed to openlog(3)
+# -p : child PID
+_daemon_args="-c -f -T ${name} -p ${pidfile}"
+# -o : (optionally) keep stdout, if we need startup diagnosis.
+[ -n "$dkwk_log" ] && _daemon_args="${_daemon_args:+"$_daemon_args "}-o ${dkwk_log}"
+command_args="${_daemon_args+"$_daemon_args "}-- ${dkwk_bin} ${command_args:+"$command_args "}${dkwk_app}"
+unset _daemon_args
 
 dkwk_env="WIKI_REPO=${dkwk_repo} WIKI_BRANCH=${dkwk_branch}"
 dkwk_start_pre () {
-	install -d -o "$dkwk_owner" -g "$dkwk_group" -m "$dkwk_run_mode" "${rundir}/${name}"
+	local _dir
+	for _dir in "/var/run/${name}" "/var/log/${name}"
+	do
+		install -d -o "$dkwk_owner" -g "$dkwk_group" -m "$dkwk_run_mode" "$_dir"
+	done
 }
 
 run_rc_command "$1"
